<article class="experiences" >
    <h2>Mes Expériences Professionelles :</h2>
    <div class="experiences-info">
        <?php foreach ($experiences as $experience): ?>
            <section class="experiences-block">
                <aside class="experiences-top">
                    <h3><?= htmlentities($experience['title'])?></h3>
                </aside>
                <aside class="experiences-bottom">
                    <h4><?= htmlentities($experience['society'])?> - <?= htmlentities($experience['city'])?></h4>
                    <p><?= htmlentities($experience['content']) ?></p>
                    <p>Période : <?= htmlentities($experience['periode']) ?></p>
                </aside>
            </section>
        <?php endforeach; ?>
    </div>
</article>