<article class="competences" >
    <h2>Mes compétences :</h2>
    <div class="competences-info">
        <?php foreach ($competences as $competence): ?>
            <section class="competences-block">
                <aside class="competences-top">
                    <img src="<?= $wwwUrl ?>/<?= $competence['path'] ?>/<?= htmlentities($competence['photo']) ?>" alt="logo <?= htmlentities($competence['title']) ?>">
                </aside>
                <aside class="competences-bottom">
                    <p><?= htmlentities($competence['title']) ?></p>
                </aside>
            </section>
        <?php endforeach; ?>
    </div>
</article>