<section class="competences" >
    <h2>Mes compétences :</h2>
    <div class="competences-info">
        <?php foreach ($competences as $competence): ?>
            <div class="competences-block">
                <div class="competences-top">
                    <img src="<?= $wwwUrl ?>/<?= $competence['path'] ?>/<?= htmlentities($competence['photo']) ?>" alt="logo <?= htmlentities($competence['title']) ?>">
                </div>
                <div class="competences-bottom">
                    <p><?= htmlentities($competence['title']) ?></p>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</section>