<article class="projects-single" >
    <div class="projects-info-single">
        <?php foreach ($projects as $project): ?>
            <section class="projects-item">
                <aside class="projects-banner">
                    <img src="<?= $wwwUrl ?>/<?= $project['path'] ?>/<?= htmlentities($project['photo']) ?>" alt="Maquette <?= htmlentities($project['title']) ?>">
                </aside>
                <aside class="projects-banner-info">
                    <h2><?= htmlentities($project['title']) ?></h2>
                    <h3>Description du projet : </h3>
                    <p><?= htmlentities($project['description']) ?></p>
                    <h4>Languages utilisés : </h4>
                    <p><?= htmlentities($project['langages']) ?></p>
                    <p><?= htmlentities($project['content']) ?></p>
                    <p>Période : <?= htmlentities($project['periode']) ?></p>

                </aside>
                <aside class="projects-single-bottom">
                    <a href="<?= $requestUrl ?>/portfolio">Retour Portfolio</a>
                </aside>
            </section>
        <?php endforeach; ?>
    </div>
</article>