<section class="home">
    <h1>DEHEM PIERRICK - Développeur Web Junior</h1>
    <div class="container-fluid flex" >
        <div class="presentation">
            <div class="col-md-8 presentation-right">
                <div class="presentation-right-img">
                    <img src="<?= $wwwUrl ?>/images/moi.jpg" alt="Photo DEHEM Pierrick">
                </div>
                <div class="presentation-info">
                    <p>Je suis diplômé d'un BTS IRIS (Informatique et Réseaux pour l'Industrie et les Services Techniques).</p>
                    <p>Je suis aujourd'hui en pleine mutation professionnelle vers le développement web.</p>
                    <p>Fin novembre 2018, j'ai terminé une formation Live intensive de 3 mois nommée "Développeur Intégrateur en réalisation d’applications web" à la <a href="https://3wa.fr/"><img src="<?= $wwwUrl ?>/images/logo_3wa.png" alt="Logo 3WAcademy"></a>.</p>

                    <p>Cette formation est basée sur 90% de pratique et 10% de théorie.</p>
                    <p>Celle-ci m'a permis d'acquérir de nombreuses compétences pour le Front-end comme le Back-end.
                    <p>Bien entendu, le monde du développement nécessite d'assimiler de nouvelles technologies comme Symfony, Angular, Vue.Js ...</p>
                    <p>Je vous invite à poursuivre la navigation sur mon site afin de voir mes compétences acquises ainsi que les projets sur lesquels j'ai travaillé.</p>
                    <br>
                    <p>Je suis également autoentrepreneur depuis le 28/12/2019. Pour toutes demandes de devis, je vous invite à me contacter directement par mail.</p>
                </div>
                <div class="clearfix"> </div>
                <div class="button-contact">
                    <a href="<?= $requestUrl ?>/contact"><i class="fas fa-envelope"></i> Contactez Moi</a>
                </div>
                <div class="social-grids">
                    <div class="social-info">
                        <h2>Suivez Moi : </h2>
                    </div>
                    <div class="social-info-links">
                         <ul>
                            <li><a href="https://www.facebook.com/pierrickdehem"><i class="fab fa-facebook fa-2x"></i></a>
                            <li><a href="https://www.linkedin.com/in/pierrick-dehem-80561aa2/"><i class="fab fa-linkedin fa-2x"></i></a></li>
                            <li><a href="https://github.com/dehemPierrick"><i class="fab fa-github fa-2x"></i></a></li>
                        </ul>
                    </div>
                    <div class="clearfix"> </div>
                </div>
            </div>
            <div class="col-md-4 presentation-left">
                <div class="presentation-left-info">
                    <h3>Prénom Nom :</h3>
                    <p><?= htmlentities($presentations['name']) ?></p>
                </div>
                <div class="presentation-left-info">
                    <h3>Age :</h3>
                    <p><?= htmlentities($age) ?> ans</p>
                </div>
                <div class="presentation-left-info">
                    <h3>Adresse :</h3>
                    <p>14, rue de la maladrerie</p>
                    <p>59181 Steenwerck, France</p>
                </div>
                <div class="presentation-left-info">
                     <h3>Adresse Email :</h3>
                     <p><a href="mailto:portfolio@pierrickdehem.ovh">portfolio@pierrickdehem.ovh</a></p>
                </div>
                <div class="presentation-left-info">
                    <h3>Tel : </h3>
                    <p><i class="fas fa-mobile-alt"></i><a href="tel:+33662600568">(+33) 06/62/60/05/68</a></p>
                </div>
            </div>
            <div class="clearfix"> </div>
            
        </div>
    </div>
</section>